In [ ]:
"""
LA1
编写一个 Python 函数，该函数计算矩阵和向量的点积。如果矩阵无法与向量进行点积，则返回 -1。
in:[[3, 5, 2], [1, 0, 4], [2, 3, 1]] ,[2, 1, 3]
out:[17, 14, 10]
------------------------
in:[[1, 2, 3], [4, 5, 6]],[1, 2]
out:-1
维度不匹配则输出-1
"""

import numpy as np


def matrix_vector_dot(matrix, vector):
    matrix = np.array(matrix)  # 转换为numpy数组
    vector = np.array(vector)  # 转换为numpy数组
    # print(matrix)
    # 转换完了直接看行列匹配吗
    print(matrix.shape, vector.shape)
    print(vector[1])
    # 需要左列等于右行，得到左行右列，列为1时，不显示
    if matrix.shape[1] != vector.shape[0]:  # 维度不匹配
        return -1
    else:
        return np.dot(matrix, vector).tolist()  # 点积结果转为列表并返回


if __name__ == "__main__":
    matrix = [[3, 5, 2], [1, 0, 4], [2, 3, 1]]
    vector = [2, 1, 3]
    print(matrix_vector_dot(matrix, vector))

In [ ]:
"""
LA2 矩阵转置，给定一个 n × m 的矩阵，请将其转置。转置是指将矩阵的行和列互换，
即原矩阵中第i行第j列的元素在转置后变为第j行第i列的元素。
in:[[1,3,5],[6,8,10]]
out:[[1,6],[3,8],[5,10]]
"""

import numpy as np
from typing import List, Union


def transpose_matrix(a: List[List[Union[int, float]]]) -> List[List[Union[int, float]]]:
    # 转置矩阵的行数和列数
    # m, n = len(a), len(a[0])
    a = np.array(a)
    # 转置矩阵有两个，a.T 和 a.transpose()，都能实现对numpy进行转置
    b = a.transpose()
    # c = a.T
    return b.tolist()


if __name__ == "__main__":
    a = [[1, 3, 5], [6, 8, 10]]
    print(transpose_matrix(a))

[[1, 6], [3, 8], [5, 10]]


In [ ]:
"""
LA3
在机器学习中,我们经常需要对矩阵进行重塑(reshape)操作。给定一个矩阵，将其重塑为一个新的矩阵，
但保持其原始数据。如果重塑前后的元素总数不相同，返回-1,重塑操作应当满足：
1.新矩阵的元素总数必须与原矩阵相同
2.原矩阵中的元素在新矩阵中的相对顺序不变
input:[[1, 2], [3, 4]],(1, 4)
output:[[1, 2, 3, 4]]
----------------
input:[[1, 2, 3]],(5, 1)
output: -1  因为元素总数不匹配
"""

from typing import List, Tuple, Union
import numpy as np


def reshape_matrix(
    a: List[List[Union[int, float]]], new_shape: Tuple[int, int]
) -> List[List[Union[int, float]]]:
    a = np.array(a)
    # prod的用法：返回数组中所有元素的乘积
    # size的用法：返回数组元素的总数
    # reshape的用法：改变数组的形状
    print(a.size, np.product(new_shape))
    # np.product(new_shape)返回new_shape的所有元素的乘积，由于其只有两个元素，所以返回总数
    # np.product可以缩写为np.prod，返回数组中所有元素的乘积
    # if a.size == np.product(new_shape): # 和下一行一样的效果
    if a.size == new_shape[0] * new_shape[1]:
        return a.reshape(new_shape).tolist()
    else:
        return -1  # 元素总数不匹配


if __name__ == "__main__":
    a = [[1, 2], [3, 4]]
    new_shape = (1, 4)
    print(reshape_matrix(a, new_shape))  # [[1, 2, 3, 4]]

    a = [[1, 2, 3]]
    new_shape = (5, 1)
    print(reshape_matrix(a, new_shape))  # -1

4 4
[[1, 2, 3, 4]]
3 5
-1


In [ ]:
"""
LA4
计算矩阵按行或按列的平均值。该函数接收一个二维数组（矩阵）和计算模式作为输入，返回对应的平均值列表。
input:[[1, 2, 3], [4, 5, 6]], row
output:[2.0, 5.0]
----------------------
input:[[1, 2, 3], [4, 5, 6]], column
output:[2.5, 3.5, 4.5]
"""

from typing import List, Union
import numpy as np


def calculate_matrix_mean(
    matrix: List[List[Union[int, float]]], mode: str
) -> List[float]:
    if mode == "row":
        return [np.mean(row) for row in matrix]
    elif mode == "column":
        # 先弄成np格式，再转置，再求均值
        return [np.mean(column) for column in np.array(matrix).T]


if __name__ == "__main__":
    matrix = [[1, 2, 3], [4, 5, 6]]
    mode = "row"
    print(calculate_matrix_mean(matrix, mode))  # [2.0, 5.0]

    matrix = [[1, 2, 3], [4, 5, 6]]
    mode = "column"
    print(calculate_matrix_mean(matrix, mode))  # [2.5, 3.5, 4.5]

[2.0, 5.0]
[2.5, 3.5, 4.5]


In [ ]:
"""
LA5
计算矩阵与标量的乘法运算。该函数接收一个二维数组（矩阵）和一个标量值作为输入，返回乘法运算后的新矩阵。
输入：[[1, 2], [3, 4]], 2.0
输出：[[2.0, 4.0], [6.0, 8.0]]
"""

from typing import List, Union
import numpy as np


def scalar_multiply(
    matrix: List[List[Union[int, float]]], scalar: Union[int, float]
) -> List[List[Union[int, float]]]:
    matrix = np.array(matrix)
    return (matrix * scalar).tolist()


if __name__ == "__main__":
    matrix = [[1, 2], [3, 4]]
    scalar = 2.0
    result = scalar_multiply(matrix, scalar)
    print(result)

[[2.0, 4.0], [6.0, 8.0]]


In [ ]:
"""
LA6
编写一个 Python 函数来计算给定向量集的协方差矩阵。该函数应该采用一个列表列表，
其中每个内部列表代表一个特征及其观察结果，并返回一个协方差矩阵。
input:[[7, 8, 9], [10, 11, 12]]
output:[[1.0, 1.0], [1.0, 1.0]]
提示：使用 numpy 库中的 cov 函数来计算协方差矩阵。
"""

import numpy as np


def calculate_covariance_matrix(vectors):
    vectors = np.array(vectors)
    return np.cov(vectors)
    # 补全代码


# 主程序
if __name__ == "__main__":
    # 输入
    ndarrayA = [[7, 8, 9], [10, 11, 12]]

    # 调用函数计算
    output = calculate_covariance_matrix(ndarrayA)

    # 输出结果
    print(output)

[[1. 1.]
 [1. 1.]]


In [ ]:
# 向量矩阵转化为对角矩阵
import torch

# 向量转化为对角矩阵
v = torch.tensor([1, 2, 3])
d = torch.diag(v)
print(d)

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


In [ ]:
"""
实现一个函数来将密集矩阵（dense matrix）转换为压缩行稀疏
(Compressed Row Sparse, CSR)格式。CSR是一种高效存储稀疏矩阵的方法，只存储非零元素及其位置信息。
input：[[1, 0, 0], [2, 3, 0], [0, 4, 5]]
output：输出三个列表，分别表示CSR格式中的values、column_indices和row_pointer。
[1, 2, 3, 4, 5]
[0, 0, 1, 1, 2]
[0, 1, 3, 5]
values：存储矩阵中所有的非零元素值
column_indices：存储每个非零元素所在的列索引
row_ptr（row pointer）：存储每行的起始位置在values中的索引
"""

import numpy as np


def dense_to_csr(dense_matrix):
    """
    将密集矩阵转换为CSR格式。
    :param dense_matrix: 密集矩阵
    :return: values, column_indices, row_pointer
    """
    values = []
    column_indices = []
    row_pointer = [0]
    for i in range(len(dense_matrix)):
        for j in range(len(dense_matrix[i])):
            if dense_matrix[i][j] != 0:
                values.append(dense_matrix[i][j])
                column_indices.append(j)
        row_pointer.append(len(column_indices))
    return values, column_indices, row_pointer


if __name__ == "__main__":
    dense_matrix = np.array([[1, 0, 0], [2, 3, 0], [0, 4, 5]])
    values, column_indices, row_pointer = dense_to_csr(dense_matrix)
    print(values)
    print(column_indices)
    print(row_pointer)

[1, 2, 3, 4, 5]
[0, 0, 1, 1, 2]
[0, 1, 3, 5]


In [4]:
"""
计算余弦相似度，保留三位小数
使用cosine_similarity函数

原代码使用整数张量([1, 2, 3])，这可能导致计算精度问题
修正为浮点张量([1.0, 2.0, 3.0])，确保计算精度
"""

import torch
import torch.nn.functional as F

# 需要是小数
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
# dim=0表示沿着第0维度计算相似度（对于一维向量），需要指定维度
cos_sim = F.cosine_similarity(a, b, dim=0)
cos_sim = round(cos_sim.item(), 3)
print(cos_sim)

0.975


泊松分布公式如下所示，其中 λ 是单位时间内事件发生的平均次数，x 是随机变量，表示事件发生的次数。
$$P(x)=\frac{\lambda^xe^{-\lambda}}{x!}$$


In [7]:
"""
编写一个 Python 函数，使用泊松分布公式计算在固定时间间隔内恰好观察到 k 个事件的概率,
该函数应将k(事件数)和λ(平均发生率)作为输入,并返回四舍五入到小数点后 5 位的概率。
输入两个整数，分别代表 k 和 λ。
输出一个浮点数，代表在固定时间间隔内恰好观察到 k 个事件的概率。
input: 3,5
output:0.14037
"""

import math


def poisson_probability(k, lam):
    val = math.exp(-lam) * math.pow(lam, k) / math.factorial(k)
    return round(val, 5)


if __name__ == "__main__":
    # k, lam = map(int, input().split())
    k, lam = 3, 5
    print(poisson_probability(k, lam))

0.14037


In [13]:
"""
点积计算器，输入两个向量，输出它们的点积。
input:[1, 2, 3], [4, 5, 6]
output:32
"""

import numpy as np


def calculate_dot_product(vec1, vec2):
    vec1 = np.array(vec1)
    vec2 = np.array(vec2)
    if vec1.shape != vec2.shape:
        raise ValueError("The two vectors should have the same shape.")
    return np.dot(vec1, vec2)


if __name__ == "__main__":
    vec1 = [1, 2, 3]
    vec2 = [4, 5, 6]
    print(calculate_dot_product(vec1, vec2))

32


矩阵的特征值是指矩阵的一些特殊的数值，这些数值可以用来表示矩阵的某种性质。矩阵的特征值和特征向量是密切相关的，公式如下，其中，$\lambda$是矩阵的特征值，$\vec{x}$是矩阵的特征向量。

$$A\vec{x}=\lambda\vec{x}$$

数学上计算特征值要先得到特征方程：

$$A\vec{x}-\lambda\vec{x} = 0$$

再使用单位矩阵，即$I$，来求解特征方程：

$$(A- \lambda I)\vec{x} = 0$$

即：$$ det(A- \lambda I) = 0$$


In [21]:
"""
计算2x2矩阵的特征值，
input:[[1,2],[2,1]]
output:[ 3. -1.]
"""

from typing import List, Union
import numpy as np


def calculate_eigenvalues(matrix: List[List[Union[int, float]]]) -> List[float]:
    matrix = np.array(matrix)
    eigenvalues = np.linalg.eigvals(matrix)
    return eigenvalues.tolist()


if __name__ == "__main__":
    matrix = [[1.0, 2.0], [2, 1]]
    eigenvalues = calculate_eigenvalues(matrix)
    # round 限制几位小数
    eigenvalues = [round(eigenvalue, 2) for eigenvalue in eigenvalues]
    # eigenvalues = round(eigenvalues[0], 2)
    print(eigenvalues)

[3.0, -1.0]


In [ ]:
import numpy as np


def inverse_2x2(matrix):
    # 转换为 numpy 数组
    matrix = np.array(matrix, dtype=float)

    # 检查是否是 2×2 矩阵
    if matrix.shape != (2, 2):
        return None
    return np.linalg.inv(matrix).tolist()


if __name__ == "__main__":
    # 输入矩阵
    matrix_input = [[2, 7], [2, 6]]

    # 调用函数计算逆矩阵
    output = inverse_2x2(matrix_input)

    # 输出结果
    print(output)

temp = np.array([[2, 7], [2, 6]])
print(np.linalg.inv(temp))

[[-3.0, 3.5], [1.0, -1.0]]
[[-3.   3.5]
 [ 1.  -1. ]]


In [46]:
"""
输入两个矩阵，返回两个矩阵做点乘的结果
input:[[2,2],[2,4]], [[2,1],[3,4]]
output:[[10,10],[16,18]]
"""

import torch

a = torch.tensor([[2, 2], [2, 4]])
b = torch.tensor([[2, 1], [3, 4]])
print(a * b) #对应元素相乘
print(a.mul(b)) #对应元素相乘
# [[10, 10], [16, 18]]
print(a.matmul(b)) #矩阵乘法

tensor([[ 4,  2],
        [ 6, 16]])
tensor([[ 4,  2],
        [ 6, 16]])
tensor([[10, 10],
        [16, 18]])


In [51]:
"""
使用雅各比Jacobi求解Ax = b的线性方程组，迭代n次，四舍五入小数点后四位
input：第1行输入A，第2行输入b，第3行输入n。
[[4, -1, 0], [-1, 4, -1], [0, -1, 3]]
[15, 10, 10]
10
out：[4.9997, 4.9997, 4.9996]
"""
import numpy as np

def solve_jacobi(A, b, n) :
    A = np.array(A)
    b = np.array(b)
    x = np.zeros(len(b))
    # 用Jacobi迭代法求解线性方程组Ax = b
    D = np.diag(np.diag(A))
    LU = A - D

    for _ in range(n):
        x = (b - np.dot(LU, x)) / np.diag(D)

    return np.round(x, 4)


if __name__ == '__main__':
    A = [[4, -1, 0], [-1, 4, -1], [0, -1, 3]]
    b = [15, 10, 10]
    n = 10
    x = solve_jacobi(A, b, n)
    print(x)

[4.9997 4.9997 4.9996]
